name: Varbase Webform Base
description: A recipe to manage default installed webform modules, configurations, and permissions for Varbase webform experience.
type: Varbase Webform
install:
  - webform
  - webform_templates
  - webform_ui
  - webform_views
  - eca_webform
  - config_perms
  - ultimate_cron
  - entity_clone
config:
  import:
    webform: '*'
    webform_templates: '*'
    webform_ui: '*'
    webform_views: '*'
  actions:
    webform.settings:
      simpleConfigUpdate:
        requirements:
          cdn: false
          clientside_validation: true
          bootstrap: true
          spam: true
    webform.webform.contact:
      simpleConfigUpdate:
        archive: true
    user.role.site_admin:
      grantPermissions:
        - 'access webform overview'
        - 'create webform'
        - 'delete any webform submission'
        - 'edit webform assets'
        - 'edit any webform'
        - 'view any webform submission'
        - 'clone webform entity'
    user.role.seo_admin:
      grantPermissions:
        - 'access webform overview'
        - 'create webform'
        - 'delete any webform submission'
        - 'edit webform assets'
        - 'edit any webform'
        - 'view any webform submission'
    user.role.content_admin:
      grantPermissions:
        - 'access webform overview'
        - 'create webform'
        - 'delete any webform submission'
        - 'edit any webform'
        - 'view any webform submission'
        - 'clone webform entity'
    user.role.editor:
      grantPermissions:
        - 'access webform overview'
        - 'create webform'
        - 'delete any webform submission'
        - 'edit webform assets'
        - 'edit any webform'
        - 'view any webform submission'
